{% set name = "trl" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1007939557b593f4b8fb177a96814b3cac468f9e706b6ac4a28fbba49c5d7555

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - trl = trl.cli:main
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
  run:
    - python
    - accelerate >=1.4.0
    - datasets >=4.7.0
    - jinja2
    - packaging >20.0
    - transformers >=4.56.2
  run_constrained:
    # deepspeed
    - deepspeed >=0.14.4
    - transformers !=5.1.0
    # liger
    - liger-kernel >=0.8.0
    # peft
    - peft >=0.8.0
    # vllm
    - vllm >=0.12.0,<=0.18.0
    - aiohttp >=3.13.3
    # vlm
    - num2words ==0.5.14
    # math_verify
    - math-verify >=0.5.2
    # openreward
    - openreward >=0.1.109  # [py>=311]
    # optional (used when installed; not required for core import/CLI)
    - rich

test:
  imports:
    - trl
  commands:
    - pip check
    - trl --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/trl
  summary: Train transformer language models with reinforcement learning.
  description: Train transformer language models with reinforcement learning.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://huggingface.co/docs/trl
  dev_url: https://github.com/huggingface/trl

extra:
  recipe-maintainers:
    - jan-janssen
