{% set name = "trl" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1007939557b593f4b8fb177a96814b3cac468f9e706b6ac4a28fbba49c5d7555

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - pytorch >=1.4.0
  run:
    - jinja2
    - packaging >20.0
    - rich
    - python
    - pytorch >=1.4.0
    - transformers >=4.56.2
    - numpy >=1.18.2
    - accelerate >=1.4.0
    - datasets >=4.7.0
    - tyro >=0.5.11

test:
  imports:
    - trl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/huggingface/trl
  summary: Train transformer language models with reinforcement learning.
  description: |
    TRL is a library for post-training foundation models with supervised fine-tuning,
    reinforcement learning, and preference optimization on top of the Hugging Face
    Transformers ecosystem.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://huggingface.co/docs/trl
  dev_url: https://github.com/huggingface/trl

extra:
  recipe-maintainers:
    - jan-janssen
